version: '3.8'

networks:
  tech_hive_backend:
    name: tech_hive_backend
    external: true

services:
  db:
    image: postgres
    container_name: storeDB
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: phumlanidev
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - tech_hive_backend
    restart: unless-stopped

  tech_hive_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech_hive_backend
    ports:
      - "9500:9500"
    networks:
      - tech_hive_backend
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg_data:
    name: pg_data