spring:
  application:
    name: Tech Hive e-Store

  datasource:
    url: jdbc:postgresql://localhost:5432/tech_hive_db
    username: ENC(rdJDby6Ae+yTpsU3c3i/T8Av4yxB8ot53mhnn8CW5oj1jrnd0y7TnYsadAafJ50d)
    password: ENC(a7DKztkGp8LfaQMEIHi9Ehiy7StMOGyjHgsEcRsRZcbkY7b/+yWfjYDgK7k34DZN)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/admin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8080
  realm: devops-realm
  resource: ecommerce
  credentials:
    secret: ENC(t8ajTobCbJBYf7UVEmmgunlGXdIHbykuHORPvMaXU7xf0jHiz3V5W6+Q7zrAAjbT0iObsO5JvNU75EDzVBJlONqiYBur+8BrMrZ4VkF1Qjo=)
  admin:
    username: admin
    password: admin

#  sql:
#    init:
#      mode: always

jwt:
  auth:
    converter:
      resource-id: ecommerce
      principle-attribute: preferred_username

logging:
  level:
    root: info
    org:
      springframework:
        web: debug

server:
  port: 7000