spring:
  application:
    name: Tech Hive e-Store

  datasource:
    url: jdbc:postgresql://localhost:5432/tech_hive_db
    username: ENC(q8r4XsDuhBzK94hghWjc3SmXw6FCUZ9/xBT0IGpV3h2/vWtTzIFp8n7DxcTPHasy)
    password: ENC(BjjwVoYkWm5iTMHGgdFZpe6dX1EPYWXCT1wkXh8tkW/uV+15Qmv8TACLty46h1yy)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/devops-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://0.0.0.0:8080/auth
  realm: devops-realm
  resource: ecommerce
  credentials:
    secret: ENC(KR/eLb6Q7NPUN+WgPkjV7sEGyq87IOquqDo5ITvBpKLyeEFMULS8SH3h7OKhZ42sIyrWOW9kIaKBJTVvjm4oVV01FRXxKK4jBwHUsM1rqNE=)

#  sql:
#    init:
#      mode: always

jwt:
  auth:
    converter:
      resource-id: ecommerce
      principle-attribute: preferred_username

logging:
  level:
    root: info
    org:
      springframework:
        web: debug

server:
  port: 7000