spring:
  application:
    name: Tech Hive e-Store

  datasource:
    url: jdbc:postgresql://localhost:5432/tech_hive_db
    username: ENC(P4ZB+ckb/Z2vGchAi5689p06EIqmOfwFnchapxGm7AovwiRGqOOI3MIOnrXouZv2)
    password: ENC(YuWGyEXvyjEz83rNyBmL5aPOjYIJBP/qd6KwzaVQj11GH4txmo5nDI9M/GWZZG7C)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/admin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8080
  realm: devops-realm
  resource: ecommerce
  credentials:
    secret: ENC(aGYEHkAXGEpbsnqHGxvI03PduzOAjPlSlLiKpQTkjLOJx9NQ+tXDtZ5ObAK+r89v/SOTsrzpPQdo++53bLooXCvvT6LQ9q1uaIAvl8rlXsM=)
  admin:
    username: admin
    password: admin

#  sql:
#    init:
#      mode: always

jwt:
  auth:
    converter:
      resource-id: ecommerce
      principle-attribute: preferred_username

logging:
  level:
    root: info
    org:
      springframework:
        web: debug

server:
  port: 7000