spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/admin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#  sql:
#    init:
#      schema-locations: classpath:schema-h2.sql
keycloak:
  auth-server-url: http://localhost:8080
  realm: mac-apps
  resource: tech-hive-store-api
  principle-attribute: preferred_username
  credentials:
    secret: ENC(v+l2EWntxAO03Ob1OXFpkSuoqTmI7cb+kOQwOVHnhPrQavklRhbUsow/l5+Ibj/jIVQO6I5+HigWyXOmw5NwtR4zY1FP4qdhzoqSd46rcQM=)
  admin:
    username: admin
    password: admin

  #  sql:
  #    init:
  #      mode: always

logging:
  level:
    root: info
    org:
      springframework:
        web: debug