spring:
  application:
    name: Tech Hive e-Store

  datasource:
    url: jdbc:postgresql://localhost:5432/tech_hive_db
    username: ENC(/nW6jbEwEA2bza/dA1QI9hwPhDqXRyU1KnrPAtQ/oMqDfmE/mP1T/uK44W7S3kCc)
    password: ENC(19JPpH3BoBvy/NO3FAvwX12J1zsAJAaglWVjR7YwhezEfik601BwD7Mb3swoD5Vu)
    driver-class-name: org.postgresql.Driver
    schema: classpath:schema-postgresql.sql
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_schema: public
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/admin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: mac-apps
  resource: ecommerce
  principle-attribute: preferred_username
  credentials:
    secret: ENC(iMzRIa4KN3yUZ9UKSfTuXcHvLkS48kI0OMv8qQ64lcZyYSp3SIhyjOk53JmFoSm3Z6qg89RwIT2eXx+dXzCMIg+Lb5pTH+LrzLngJPvOTdw=)
  admin:
    username: admin
    password: admin

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

server:
  port: 9000