spring:
  application:
    name: Tech Hive e-Store

  datasource:
    url: jdbc:postgresql://localhost:5432/tech_hive_db
    username: macgyver
    password: Chr1st1@n9432
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.18.0.2:8080/admin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://172.18.0.2:8080/
  realm: mac-apps
  resource: ecommerce
  credentials:
    secret: Bw421P4VwyPsBj8vthwOQiIJ4WyCznSr
  admin:
    username: admin
    password: admin

#  sql:
#    init:
#      mode: always

jwt:
  auth:
    converter:
      resource-id: ecommerce
      principle-attribute: preferred_username

logging:
  level:
    root: info
    org:
      springframework:
        web: debug

server:
  port: 9000