name: Build-Test-Analyze Code

permissions:
  issues: read
  contents: read
  actions: read

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop, main ]

jobs:
  setup:
    uses: PhumlaniDev/reusable-workflows/.github/workflows/java-maven-setup.yml@main

  checkstyle:
    runs-on: ubuntu-latest
    needs: [ setup ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        run: mvn --batch-mode checkstyle:check

  debug-cache-key:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Debug Cache Key
        run:
          echo "Cache Key: ${{ needs.setup.outputs.cache-key }}"

  build:
    needs: [ checkstyle ]
    uses: PhumlaniDev/reusable-workflows/.github/workflows/java-maven-build-test.yml@main
    with:
      project_name: tech-hive-store
      database_name: tech_hive_db
      test_database_name: tech_hive_test_db
      cache-key: ${{ needs.setup.outputs.cache-key }}

#  unit_tests:
#    runs-on: ubuntu-latest
#    needs: [ build ]
#
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v4
#
#      - name: Restore Maven cache
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
#
#      - name: Run unit tests with H2 database
#        run: mvn --batch-mode test
#        env:
#          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
#          SPRING_DATASOURCE_USERNAME: test
#          SPRING_DATASOURCE_PASSWORD: test
#          JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
#
#  code_analysis:
#    runs-on: ubuntu-latest
#    needs: [ build ]
#    uses: PhumlaniDev/reusable-workflows/.github/workflows/java-code_analysis.yml
#    with:
#      project_key: ${{ secrets.SONAR_PROJECT_KEY }}
#  #  integration_test:
#  #    runs-on: ubuntu-latest
#  #    needs: [ code_analysis ]
#  #    services:
#  #      postgres:
#  #        image: postgres:latest
#  #        ports:
#  #          - 5432:5432
#  #        env:
#  #          POSTGRES_DB: techhive
#  #          POSTGRES_USER: phumlanidev
#  #          POSTGRES_PASSWORD: password
#  #        options: >-
#  #          --health-cmd "pg_isready -U $POSTGRES_USER"
#  #          --health-interval 10s
#  #          --health-timeout 5s
#  #          --health-retries 5
#  #
#  #    steps:
#  #      - name: Check out code
#  #        uses: actions/checkout@v4
#  #
#  #      - name: Set up Java
#  #        uses: actions/setup-java@v4
#  #        with:
#  #          distribution: 'zulu'
#  #          java-version: '17'
#  #
#  #      - name: Restore Maven cache
#  #        uses: actions/cache@v4
#  #        with:
#  #          path: ~/.m2/repository
#  #          key: ${{ needs.setup.outputs.cache-key }}
#  #
#  #      - name: Restore Maven cache
#  #        uses: actions/cache@v4
#  #        with:
#  #          path: ~/.m2/repository
#  #          key: ${{ needs.setup.outputs.cache-key }}
#  #
#  #      - name: Wait for Postgres
#  #        run: |
#  #          until pg_isready -h localhost -p 5432; do
#  #          echo "Waiting for PostgreSQL..."
#  #          sleep 2
#  #          done
#  #
#  #      - name: Run Integration Tests
#  #        run: mvn verify -Dspring.profiles.active=test
#
#  vulnerability_scan:
#    runs-on: ubuntu-latest
#    needs: [ code_analysis ]
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v4
#
#      - name: Cache Trivy database
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/trivy
#          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            trivy-db-
#
#      - name: Install Trivy
#        run: |
#          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
#
#      - name: Run Trivy vulnerability scan
#        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .
#
#      - name: Log in to Docker Hub
#        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
#
#      - name: Pull Docker Image
#        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tech-hive-store:${{ github.run_number }}
#
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@0.20.0
#        with:
#          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/tech-hive-store:${{ github.run_number }}
#          format: 'table'
#          exit-code: '0'
#          ignore-unfixed: true
#          vuln-type: 'os,library'
#          severity: 'CRITICAL,HIGH'
#        env:
#          GH_PAT: ${{ secrets.GH_PAT }}
#
#  publish_nexus:
#    runs-on: ubuntu-latest
#    needs: [ vulnerability_scan ]
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v4
#
#      - name: Debug Cache Key
#        run: echo "${{ steps.cache-dependencies.outputs.cache-key }}"
#
#      - name: Restore Maven cache
#        uses: actions/cache@v4
#        with:
#          path: ~/.m2/repository
#          key: ${{ needs.setup.outputs.cache-key || 'default-key' }}
#          fail-on-cache-miss: false
#
#      - name: Deploy Maven Artifacts to GitHub Packages
#        if: github.ref != 'refs/heads/devlop'
#        run: mvn deploy -DskipTests --settings .github/settings.xml
#
#        env:
#          GH_PAT: ${{ secrets.GH_PAT }}
#          GH_USERNAME: ${{ secrets.GH_USERNAME }}
#
#  job-summary:
#    runs-on: ubuntu-latest
#    needs: [ publish_nexus ]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Generate code analysis report
#        run: curl -u ${{ secrets.SONAR_TOKEN }} https://sonarcloud.io/api/project_analyses/search?project=${{ secrets.SONAR_PROJECT_KEY }} -o sonar-report.json
#
#      - name: Generate vulnerability report
#        run: cat trivy-report.json | jq '.'
#
#      - name: Create summary table
#        run: |
#          echo "# Analysis and Vulnerability Report" > report.md
#          echo "## SonarCloud Analysis" >> report.md
#          cat sonar-report.json | jq . >> report.md
#          echo "## Vulnerabilities" >> report.md
#          cat trivy-report.json | jq -r '.[] | "Package: \(.Target)\nSeverity: \(.Severity)\nDescription: \(.VulnerabilityID)\n"' >> report.md
#
#      - name: Upload summary
#        uses: actions/upload-artifact@v4
#        with:
#          name: summary-report
#          path: report.md