name: Dependabot Discord Notification

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize
    branches:
      - develop  # Your dependabot PRs target branch

permissions:
  contents: read
  pull-requests: read

jobs:
  notify:
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    uses: ./.github/workflows/discord-notify.yml
    with:
      status: success
      title: "🤖 Dependabot PR: ${{ github.event.action | capitalize }}"
      description: |
        **Dependabot PR Notification**
        - PR: #${{ github.event.pull_request.number }}
        - Title: `${{ github.event.pull_request.title }}`
        - State: `${{ github.event.pull_request.state }}`
        - Author: `${{ github.actor }}`
        [View PR](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})
      color: '7506394'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}